sudo: required
language: java
dist: trusty
jdk: oraclejdk8
install: mvn dependency:resolve
cache:
  directories:
  - "$HOME/bin"
  - "$HOME/.m2"
notifications:
  slack:
    secure: rd5Ga3K3CaWcGj/xvtgYaocrgVBuhbh/OUwBWEePoq6d5VDb3RpLTUeDTShzqB7D1sh2kwOgVxVKqFLyD/YIrnYdzCRxC9EGR/YTFnFXeRlfErLR2awlxxL4+2/YVZPaSz6izsPqMCEpF0+C/PCJTeUikHhwMKUTEJz45IfLKaCVw1qjU/iUvUEefA6fAq5DmuS+x4HHBxluvqVMPXeQeUBNsQJ/iS1xKWNi5oj+jQutegZAcuf+fTUQwFSZIvsZwKf0JFuiJD7QF+kKp2dDKWglMPqv5ymvkhXL4j+DC7pF8jE2RGZejuU5vQJCpKsJKV8TNVkUj7aPR/12bAB+Q7Et1UbuR7FxThjNhdl9M0BCD85beMT0SYIM0y9Eixk8yLqnBbbGSFkJt7kd5dvzU2UsCe/9jAWjkBFjAWFpADRBmEg+Ag1Y2YdHBlMtcJ7FyuV2OJmJhsGgX1GoqNdtl2Yzco4rTt8LUCB+wHMHhIKTPQNXF08LPzue/U+cvv84F6M7pvkGs8j/a9z3ui0t7B2k2+2rbDAotQbZDKD0BZIK7Hf65hGdyzGDkwVBYYnPd3zSLVgrdYHXbJeD9aDbjz1BXUDz/ryqsugfS/6YOuT+DKwjwYFhcFi8LaIpa1Sgfit4EHNIeBMrhgucWCe/Y+0C902+yUruagDNlV3gXd4=
  email: false
addons:
  sonarcloud:
    organization: mediusinc
script:
- mvn package
